version: "3.8"
services:
  master:
    build: ./master
    ports: 
      - '5000:5000'
    volumes:
      - file_data:/app/data
  checksum:
    build: ./models/checksum
    # ports:
    #   - '5001:5001'
    volumes:
      - file_data:/app/data

volumes:
  file_data: